### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by unwiredben**
Add emery support... you'll have to update npm too :)

### CODE REVIEW

**Comment by C-D-Lewis** [comment]
Thanks, but I don't think dist.zip needs to be tracked in git. I will of course generate it before publishing.

**Comment by unwiredben** [comment]
I'll kill the dist.zip... I thought I saw it in the repo already.

**Comment by unwiredben** [comment]
OK, repushed with that taken out

**Comment by C-D-Lewis** [comment]
Thanks! Publishing now.

**Pull request merged**
